#!/bin/bash

function user_details {
	echo "User Name: $(whoami)"
	echo "Home Directory: $HOME"
	echo ID: "$(id)"
	lslogins -u
}

echo "Good Morning! Sleep Well?"

CURRENT_DATE=$(date +"%d-%m-%Y")
echo "The date is" $CURRENT_DATE
CURRENT_TIME=$(date +"%H:%M:%S")
echo "The current time is" $CURRENT_TIME
toilet Good Morning!

user_details
